import Head from "next/head";

import { Inter } from "@next/font/google";
import { Header } from "components/Header/Header";
import { HeroOverlay } from "components/Layouts.tsx/HeroOverlay";
import { Hero } from "components/Hero/Hero";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mental Health Awareness Fundraiser</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <div className="bg-slate-200">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel odio
        ducimus nobis eius cumque quibusdam vero reprehenderit dolorem labore ut
        nulla facilis est voluptatum amet asperiores nostrum, dignissimos omnis!
        Numquam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel
        odio ducimus nobis eius cumque quibusdam vero reprehenderit dolorem
        labore ut nulla facilis est voluptatum amet asperiores nostrum,
        dignissimos omnis! Numquam. Lorem ipsum dolor sit amet, consectetur
        adipisicing elit. Vel odio ducimus nobis eius cumque quibusdam vero
        reprehenderit dolorem labore ut nulla facilis est voluptatum amet
        asperiores nostrum, dignissimos omnis! Numquam. Lorem ipsum dolor sit
        amet, consectetur adipisicing elit. Vel odio ducimus nobis eius cumque
        quibusdam vero reprehenderit dolorem labore ut nulla facilis est
        voluptatum amet asperiores nostrum, dignissimos omnis! Numquam. Lorem
        ipsum dolor sit amet, consectetur adipisicing elit. Vel odio ducimus
        nobis eius cumque quibusdam vero reprehenderit dolorem labore ut nulla
        facilis est voluptatum amet asperiores nostrum, dignissimos omnis!
        Numquam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel
        odio ducimus nobis eius cumque quibusdam vero reprehenderit dolorem
        labore ut nulla facilis est voluptatum amet asperiores nostrum,
        dignissimos omnis! Numquam. Lorem ipsum dolor sit amet, consectetur
        adipisicing elit. Vel odio ducimus nobis eius cumque quibusdam vero
        reprehenderit dolorem labore ut nulla facilis est voluptatum amet
        asperiores nostrum, dignissimos omnis! Numquam. Lorem ipsum dolor sit
        amet, consectetur adipisicing elit. Vel odio ducimus nobis eius cumque
        quibusdam vero reprehenderit dolorem labore ut nulla facilis est
        voluptatum amet asperiores nostrum, dignissimos omnis! Numquam. Lorem
        ipsum dolor sit amet, consectetur adipisicing elit. Vel odio ducimus
        nobis eius cumque quibusdam vero reprehenderit dolorem labore ut nulla
        facilis est voluptatum amet asperiores nostrum, dignissimos omnis!
        Numquam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel
        odio ducimus nobis eius cumque quibusdam vero reprehenderit dolorem
        labore ut nulla facilis est voluptatum amet asperiores nostrum,
        dignissimos omnis! Numquam. Lorem ipsum dolor sit amet, consectetur
        adipisicing elit. Vel odio ducimus nobis eius cumque quibusdam vero
        reprehenderit dolorem labore ut nulla facilis est voluptatum amet
        asperiores nostrum, dignissimos omnis! Numquam. Lorem ipsum dolor sit
        amet, consectetur adipisicing elit. Vel odio ducimus nobis eius cumque
        quibusdam vero reprehenderit dolorem labore ut nulla facilis est
        voluptatum amet asperiores nostrum, dignissimos omnis! Numquam. Lorem
        ipsum dolor sit amet, consectetur adipisicing elit. Vel odio ducimus
        nobis eius cumque quibusdam vero reprehenderit dolorem labore ut nulla
        facilis est voluptatum amet asperiores nostrum, dignissimos omnis!
        Numquam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel
        odio ducimus nobis eius cumque quibusdam vero reprehenderit dolorem
        labore ut nulla facilis est voluptatum amet asperiores nostrum,
        dignissimos omnis! Numquam. Lorem ipsum dolor sit amet, consectetur
        adipisicing elit. Vel odio ducimus nobis eius cumque quibusdam vero
        reprehenderit dolorem labore ut nulla facilis est voluptatum amet
        asperiores nostrum, dignissimos omnis! Numquam. Lorem ipsum dolor sit
        amet, consectetur adipisicing elit. Vel odio ducimus nobis eius cumque
        quibusdam vero reprehenderit dolorem labore ut nulla facilis est
        voluptatum amet asperiores nostrum, dignissimos omnis! Numquam. Lorem
        ipsum dolor sit amet, consectetur adipisicing elit. Vel odio ducimus
        nobis eius cumque quibusdam vero reprehenderit dolorem labore ut nulla
        facilis est voluptatum amet asperiores nostrum, dignissimos omnis!
        Numquam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel
        odio ducimus nobis eius cumque quibusdam vero reprehenderit dolorem
        labore ut nulla facilis est voluptatum amet asperiores nostrum,
        dignissimos omnis! Numquam. Lorem ipsum dolor sit amet, consectetur
        adipisicing elit. Vel odio ducimus nobis eius cumque quibusdam vero
        reprehenderit dolorem labore ut nulla facilis est voluptatum amet
        asperiores nostrum, dignissimos omnis! Numquam. Lorem ipsum dolor sit
        amet, consectetur adipisicing elit. Vel odio ducimus nobis eius cumque
        quibusdam vero reprehenderit dolorem labore ut nulla facilis est
        voluptatum amet asperiores nostrum, dignissimos omnis! Numquam. Lorem
        ipsum dolor sit amet, consectetur adipisicing elit. Vel odio ducimus
        nobis eius cumque quibusdam vero reprehenderit dolorem labore ut nulla
        facilis est voluptatum amet asperiores nostrum, dignissimos omnis!
        Numquam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel
        odio ducimus nobis eius cumque quibusdam vero reprehenderit dolorem
        labore ut nulla facilis est voluptatum amet asperiores nostrum,
        dignissimos omnis! Numquam. Lorem ipsum dolor sit amet, consectetur
        adipisicing elit. Vel odio ducimus nobis eius cumque quibusdam vero
        reprehenderit dolorem labore ut nulla facilis est voluptatum amet
        asperiores nostrum, dignissimos omnis! Numquam. Lorem ipsum dolor sit
        amet, consectetur adipisicing elit. Vel odio ducimus nobis eius cumque
        quibusdam vero reprehenderit dolorem labore ut nulla facilis est
        voluptatum amet asperiores nostrum, dignissimos omnis! Numquam. Lorem
        ipsum dolor sit amet, consectetur adipisicing elit. Vel odio ducimus
        nobis eius cumque quibusdam vero reprehenderit dolorem labore ut nulla
        facilis est voluptatum amet asperiores nostrum, dignissimos omnis!
        Numquam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel
        odio ducimus nobis eius cumque quibusdam vero reprehenderit dolorem
        labore ut nulla facilis est voluptatum amet asperiores nostrum,
        dignissimos omnis! Numquam. Lorem ipsum dolor sit amet, consectetur
        adipisicing elit. Vel odio ducimus nobis eius cumque quibusdam vero
        reprehenderit dolorem labore ut nulla facilis est voluptatum amet
        asperiores nostrum, dignissimos omnis! Numquam. Lorem ipsum dolor sit
        amet, consectetur adipisicing elit. Vel odio ducimus nobis eius cumque
        quibusdam vero reprehenderit dolorem labore ut nulla facilis est
        voluptatum amet asperiores nostrum, dignissimos omnis! Numquam. Lorem
        ipsum dolor sit amet, consectetur adipisicing elit. Vel odio ducimus
        nobis eius cumque quibusdam vero reprehenderit dolorem labore ut nulla
        facilis est voluptatum amet asperiores nostrum, dignissimos omnis!
        Numquam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel
        odio ducimus nobis eius cumque quibusdam vero reprehenderit dolorem
        labore ut nulla facilis est voluptatum amet asperiores nostrum,
        dignissimos omnis! Numquam. Lorem ipsum dolor sit amet, consectetur
        adipisicing elit. Vel odio ducimus nobis eius cumque quibusdam vero
        reprehenderit dolorem labore ut nulla facilis est voluptatum amet
        asperiores nostrum, dignissimos omnis! Numquam. Lorem ipsum dolor sit
        amet, consectetur adipisicing elit. Vel odio ducimus nobis eius cumque
        quibusdam vero reprehenderit dolorem labore ut nulla facilis est
        voluptatum amet asperiores nostrum, dignissimos omnis! Numquam. Lorem
        ipsum dolor sit amet, consectetur adipisicing elit. Vel odio ducimus
        nobis eius cumque quibusdam vero reprehenderit dolorem labore ut nulla
        facilis est voluptatum amet asperiores nostrum, dignissimos omnis!
        Numquam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel
        odio ducimus nobis eius cumque quibusdam vero reprehenderit dolorem
        labore ut nulla facilis est voluptatum amet asperiores nostrum,
        dignissimos omnis! Numquam. Lorem ipsum dolor sit amet, consectetur
        adipisicing elit. Vel odio ducimus nobis eius cumque quibusdam vero
        reprehenderit dolorem labore ut nulla facilis est voluptatum amet
        asperiores nostrum, dignissimos omnis! Numquam. Lorem ipsum dolor sit
        amet, consectetur adipisicing elit. Vel odio ducimus nobis eius cumque
        quibusdam vero reprehenderit dolorem labore ut nulla facilis est
        voluptatum amet asperiores nostrum, dignissimos omnis! Numquam. Lorem
        ipsum dolor sit amet, consectetur adipisicing elit. Vel odio ducimus
        nobis eius cumque quibusdam vero reprehenderit dolorem labore ut nulla
        facilis est voluptatum amet asperiores nostrum, dignissimos omnis!
        Numquam.
      </div>
    </>
  );
}
