import Head from "next/head";

import { LandingPage } from "components/LandingPage/LandingPage";
import { GetServerSideProps } from "next";
import { getSession } from "next-auth/react";

export type HomeProps = {
  data: {
    user: {
      firstName: string;
      lastName: string;
      email: string;
      id: number;
    };
  };
};

export default function Home({ data }: HomeProps) {
  return (
    <>
      <Head>
        <title>Mental Health Awareness Fundraiser</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage data={data?.user} />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession({ req: context.req });

  if (!session) {
    return {
      props: {
        data: null,
      },
    };
  } else {
    return {
      props: {
        data: session,
      },
    };
  }
};
